apiVersion: v1
kind: Service
metadata:
  name: mhs-frontend-service
  namespace: default
spec:
  selector:
    app: mhs-frontend  # Hier das Label anpassen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Optional, standardmäßig ist es ClusterIP
